
var express = require('express');
var router = express.Router();
var app = express();
const nodemailer = require("nodemailer");
var mailer = require('express-mailer');
var cors = require('cors');
var path = require('path');
var bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(cors());

var port = process.env.PORT || 3000;

//Static Folder
app.use('/src', express.static(path.join(__dirname, 'src')));

app.get('/', (req, res) => {
    res.send('Welcome to Node API')
})

app.get('/test', (req, res) => {
    console.log('get');
})

app.post('/sendemail', (req, res, next) => {
    console.log(req);
    // create reusable transporter object using the default SMTP transport
    let transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 465,
        secure: true, // true for 465, false for other ports
        auth: {
            user: 'bilmolas@gmail.com', // generated ethereal user
            pass: 'bilmolasbilmolas' // generated ethereal password
        },
        tls: {
            rejectUnauthorized: false
        }
    });

    // setup email data with unicode symbols
    if (req.body.type == 'workpemit') {

        for(i=0; i<req.body.email.length; i++){
            console.log(req.body.email[i]);
            let mailOptions = {
                from: '"NOG" <bilmolas@gmail.com>', // sender address
                to: req.body.email[i] + ",baz@example.com", // list of receivers
                subject: "Work Permit For " + req.body.facility, // Subject line
                text: "A Work Permit has just being generated by " + req.body.name + " of " + req.body.department + " department " + " for " + req.body.description + " at " + req.body.location + "/" + req.body.facility + " wrokpermit number is " + req.body.ptwno + " you can contact the operator on " + req.body.phoneNumber, // plain text body
                //html: "<b>Hello world?</b>" // html body
            };
            // send mail with defined transport object
            let info = transporter.sendMail(mailOptions, (error, info) => {
                if (error) {
                    return console.log(error);
                }
                console.log("Message sent: %s", info.messageId);
                // Preview only available when sending through an Ethereal account
                console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));

                // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>
                // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
            })
        }
    }

    else if (req.body.type == 'approve') {
        let mailOptions = {
            from: '"NOG" <bilmolas@gmail.com>', // sender address
            to: req.body.email, // list of receivers
            subject: "Work Permit For " + req.body.facility + " has been approved ", // Subject line
            text: "Your Work Permit of number " + req.body.ptwno + " has been approved by " + req.body.name + " of " + req.body.department + " department " + " for " + req.body.description + " at " + req.body.location + "/" + req.body.facility + " you can contact the approver on " + req.body.phoneNumber, // plain text body
            //html: "<b>Hello world?</b>" // html body
        };

        // send mail with defined transport object
        let info = transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                return console.log(error);
            }
            console.log("Message sent: %s", info.messageId);
            // Preview only available when sending through an Ethereal account
            console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));

            // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>
            // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
        })
    }

    else if (req.body.type == 'disapprove') {
        let mailOptions = {
            from: '"NOG" <bilmolas@gmail.com>', // sender address
            to: req.body.email, // list of receivers
            subject: "Work Permit For " + req.body.facility + " has been disapproved ", // Subject line
            text: "Your Work Permit of number " + req.body.ptwno + " has been disapproved by " + req.body.name + " of " + req.body.department + " department " + " for " + req.body.description + " at " + req.body.location + "/" + req.body.facility + " you can contact the disapprover on " + req.body.phoneNumber, // plain text body
            //html: "<b>Hello world?</b>" // html body
        };

        // send mail with defined transport object
        let info = transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
                return console.log(error);
            }
            console.log("Message sent: %s", info.messageId);
            // Preview only available when sending through an Ethereal account
            console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));

            // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>
            // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
        })
    }

})

app.listen(port);
console.log("Server started at port " + port);
