
export interface Dailyreport {
    id?: string,
    rev?: string,
    datecreated: any,
    staffid: string,
    staffname: string,
    department: string,
    optrain1: any,
    optrain2: any,
    opsurgevessel: string,
    otnpdc: string,
    tgngc: any,
    tghp: string,
    tglp: any,
    tvfuelgas: any,
    gascompressor1: string,
    gascompressor2: any,
    pt1: string,
    pt2: string,
    iaircompressora: any,
    iaircompressorb: any,
    gasgen1: any,
    gasgen3: string,
    gasgen4: string,
    gasgen5: string,
    dieselgenset: string,
    dailyactivities: any
}
