
export interface Faultregistry {
    id?: string,
    rev?: string,
    datecreated: Date,
    location: string,
    faultid: any,
    equipmentpartname: string,
    equipmentpartid: any,
    equipmentcatid: any,
    equipmentcatname: string,
    color: string,
    faculty: any,
    description: string,
    status: any,
    department: any,
    post: string,
    datefixed: any,
    staff: string,
    staffid: string,
    beepstatus: any,
    animateswitch: any,
    fixedstatus: any,
    tagname: string,
    tagid: string,
    name: string,
    equipmenttag: string,
    operatorstatus: any,
    supervisorstatus: any,
    managerstatus: any,
    picture: any,
    fixed: any
}
