
export interface Workorder {
    id?: string,
    rev?: string,
    workorderno: any,
    worktypes: string,
    tagname: string,
    tagid: any,
    equipmentpartname: string,
    equipmentpartid: any,
    equipmentcatid: any,
    equipmentcatname: string,
    name: string,
    faculty: any,
    exactlocation: string,
    description: string,
    workprocedure: string,
    precautions: string,
    priority: string,
    responsibility: string,
    frequency: number,
    status: any,
    department: any;
    datewo: any,
    datecreated: any,
    post: string,
    frequencyspandate: any,
    staff: string,
    staffid: string,
    frequencydate: any,
    beepstatus: any,
    animateswitch: string,
    gstatus: any,
    woid: any,
    dstatus: any
}
